language: node_js
services:
  - mongodb
node_js: 
  - "node"
before_script:
  - sudo apt-get install libtbb-dev
  - mkdir uploads
  - mkdir ~/references
  - cp public/test/testReference.fasta ~/references/
  - git clone https://github.com/BenLangmead/bowtie.git
  - cd bowtie && make && sudo make install && cd ..
  - bowtie-build --verbose -f ~/references/testReference.fasta ~/references/testReference
  - git clone https://git.code.sf.net/p/samstat/code samstat-code
  - cd samstat-code/src
  - sed -r "s/(.?\(CC\)).?(.?\(CFLAGS\)).?(.?\(LD\)).?(.?\(OBJECTS\)).?(-o .?\(PROGS\))/\1 \2 \4 \5 \3/g" Makefile > Makefile
  - make && sudo make install
