language: node_js
services:
  - mongodb
node_js: 
  - "node"
before_script:
  - mkdir uploads
  - git clone https://github.com/markonyango/quasi-tools.git
  - sh ./quasi-tools/install.sh
  - pwd
  - bowtie-build -f ./public/test/testReference.fasta ~/references/testReference