language: node_js
services:
  - mongodb
node_js: 
  - "node"
before_script:
  - mkdir uploads
  - mkdir ~/references
  - cp public/test/testReference.fasta ~/references/
  - git clone https://github.com/markonyango/quasi-tools.git
  - sh ./quasi-tools/install.sh
  - bowtie-build --verbose -f ~/testReference.fasta ~/references/testReference