language: node_js
services:
  - mongodb
node_js: 
  - "node"
before_script:
  - mkdir uploads
  - mkdir ~/references
  - git clone https://github.com/markonyango/quasi-tools.git
  - sh ./quasi-tools/install.sh
  - /home/travis/bin/bowtie-build -f /home/travis/build/markonyango/quasi-express/public/test/testReference.fasta /home/travis/references/testReference